### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by xousef** [DrelezTM/StickerWhatsAppBOT#8]
C:\Users\User\StickerWhatsAppBOT>npm start

> stickerbot@1.4.0 start C:\Users\User\StickerWhatsAppBOT
> node .

C:\Users\User\StickerWhatsAppBOT\node_modules\whatsapp-web.js\src\Client.js:1354
                if ((await window.Store.QueryExist(pWid))?.wid) participantWids.push(pWid);
                                                          ^

SyntaxError: Unexpected token '.'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\Users\User\StickerWhatsAppBOT\node_modules\whatsapp-web.js\index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stickerbot@1.4.0 start: `node .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stickerbot@1.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2023-10-26T07_10_27_208Z-debug.log

C:\Users\User\StickerWhatsAppBOT>

**Comment by DrelezTM** [comment]
please update the latest version, or you can follow the steps listed [Here](https://github.com/DrelezTM/StickerWhatsAppBOT/issues/9)
